### PR TITLE
Fix #270

### LINKED ISSUE #270: Incorrect import path for descriptor.proto
`descriptor/descriptor.go` depends on `"google.golang.org/genproto/protobuf"` for proto artifacts generated from [descriptor.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto).  The import path should instead be `github.com/golang/protobuf/protoc-gen-go/descriptor`.

CC https://github.com/google/go-genproto/issues/18

### PR DESCRIPTION
**Pull request by natefinch**
This changes the import path to import from github.com/golang
instead of google.golang.org

Fixes #270

### CODE REVIEW

File: descriptor/descriptor.go [hunk 1]
```diff
@@ -42,8 +42,8 @@ import (
 	"fmt"
 	"io/ioutil"
 
+	protobuf "github.com/golang/protobuf/descriptor"
```
Comment (lazyhackeratwork) [inline descriptor/descriptor.go]: Should this be: `protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"`?

Same change in descriptor_test.go

Comment (natefinch) [inline descriptor/descriptor.go]: oops!  yes, thanks for catching that.

Comment (natefinch) [inline descriptor/descriptor.go]: Fixed.

**Comment by natefinch** [comment]
ping

**Comment by neild** [comment]
Sorry for the delay.
